# Generated by Django 5.0.14 on 2025-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_petpassbook'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vaccination',
            name='vaccination_patient_4f6731_idx',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='medical_record',
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='administered_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='certificate_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date_administered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='vaccination',
            table=None,
        ),
    ]
