# Generated by Django 5.0 on 2026-01-30 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_prescription_options_remove_prescription_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='dogger_prescriptions',
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
                'db_table': 'dogger_prescription_items',
                'ordering': ['created_at'],
            },
        ),
    ]
