# Generated by Django 5.0 on 2026-02-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_prescription_medicines_prescription_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
